[package]
name = "datis-core"
version = "2.2.0-beta.6"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
audiopus = "0.2"
base64 = "0.13"
bytes = "1.0"
dcs-module-ipc = { version = "0.3", optional = true }
futures = "0.3"
log = "0.4"
ogg = "0.7"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
rusoto_core = "0.46"
rusoto_credential = "0.46"
rusoto_polly = "0.46"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
srs = { path = "../srs" }
thiserror = "1.0"
tokio = { version = "1.0", features = ["time", "rt-multi-thread", "sync"] }

[target.'cfg(target_os = "windows")'.dependencies]
win-tts = { path = "../win-tts" }

[features]
default = []
ipc = ["dcs-module-ipc"]