[package]
name = "win-tts"
version = "2.2.0-beta.6"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.0", features = ["macros"] }
win-media = { path = "../win-media" }