name: Rust

on: push

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update Rust
      run: rustup update
    - name: Run tests
      run: make test
    - name: Codestyle
      run: cargo fmt -- --check
